import { Router } from 'express';
import { createProject, getAllProjects, getProjectById, updateProject, deleteProject, deleteAllProjects } from '../controllers/projectController.js';
const router = Router();
router.get('/', getAllProjects);
router.get('/:id', getProjectById);
router.post('/', createProject);
router.put('/:id', updateProject);
router.delete('/:id', deleteProject);
router.delete('/', deleteAllProjects);
export default router;
